### ISSUE TITLE
Some improvements to make it easier to build and to use...

### ISSUE THREAD

**Issue by rin67630** [seurat-atreides/RICOH_SP-204_Toner-Chip-Reset#2]
May I suggest some improvements:

a) I had to replace 
toner_chip.begin(toner_chip.twiClock800kHz);
by 
toner_chip.begin(toner_chip.twiClock100kHz);
else it did not compile.

b) It compiled and runs fine on a Wemos D1 Mini, which is more convenient to use since it needs no adapter.
c) I made a contact comb using gold feather wires from a RJ12 connector and soldering them on a piece of prototyping PCB.
cf attachment
![RicohSP200_resetter](https://user-images.githubusercontent.com/14197155/102669550-29a8f700-418f-11eb-9d13-fa6fc9c15f8c.jpg)

d) I changed the setup to perform a chip reset automatically 2 seconds after the reset of the Wemos. 

That way, you need no computer connected: just feed the Wemos D1 with an USB charger, apply the contact comb on the cartridge, press the reset switch and wait 4 seconds.
That's it.
You can reset many cartridges on one batch, just press reset in between.

If you want to dump data on the monitor instead of resetting, just ensure that the comb is applied to the chip at earliest 4 seconds **after** the Wemos has started.

**Comment by rin67630** [comment]
setup change:
```
void setup(void) {
  Serial.begin(9600);
  Serial.println("Initializing I2C bus");
  byte i2cStat = toner_chip.begin(toner_chip.twiClock100kHz);
  if ( i2cStat != 0 ) {
    Serial.println("I2C bus init error");
  }
  else {
    Serial.println("I2C bus initalized");
  }
  displayHelp();

  Serial.println("Resetting the chip in 3 seconds");

  delay(2000);

  Serial.println("Reseting the toner chip");
  reset();
  Serial.println("Reset done");

}
```

**Comment by seurat-atreides** [comment]
Hi rin67630,

thanks for your valuable contribution. I will get me a Wemos D1 and build one like you have built.
If you have the time I would appreciate it if you could branch and send a pull request.

**Comment by rin67630** [comment]
Hi Seurat,
unfortunately, I could not create a branch, I probably need your authorization for that. 
But I forked your project, and you can follow the fork, retrieving my stuff from there.
Meanwhile I have added the option to reset SP150 cartridges as well.
Regards.
Laszlo
