### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by lysy83** [seurat-atreides/RICOH_SP-204_Toner-Chip-Reset#5]
Hi, could I get any contact to you. I want to ask some things about Ricoh reseter

**Comment by seurat-atreides** [comment]
Sure, what would you like to ask?

**Comment by lysy83** [comment]
I have exactly the same chip, but it is for Inkjet printer.

I could share old and new chips with you. Could you do a reseter for me. I
need it commercially and I would be happy to pay.

śr., 14 cze 2023, 17:08 użytkownik Seurat ***@***.***>
napisał:

**Comment by seurat-atreides** [comment]
I can't help you with that since I don't do commercial work of this type.
Look in China for professional flash memory programming equipment.

**Comment by seurat-atreides** [comment]
Closed
